CREATE TABLE users ( 
    id SERIAL PRIMARY KEY, 
    username TEXT UNIQUE NOT NULL, 
    email TEXT UNIQUE NOT NULL, 
    password TEXT NOT NULL, 
    createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    updatedat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
    );
